mining:
  key:
  organisation:
  secret:
ticker:
  currency: litecoin,ravencoin,bitcoin,ethereum,stellar,bitcoin-cash,monero,mithril
  fiatcurrency: cad
  sparklinedays: 7
  updatefrequency: 30
colours:
  nicehash: orange
  date: black
  price: black
  days: black
