colours:
  date: black
  days: black
  nicehash: orange
  price: black
  #sparkline colours are single letter rgbk
  sparkline: k
  point: r
  axline: k
  bg: white
mining:
  key:
  organisation:
  secret:
ticker:
  currency: litecoin,ravencoin,bitcoin,ethereum,stellar,bitcoin-cash,monero,mithril
  fiatcurrency: cad
  sparklinedays: 7
  updatefrequency: 30
